# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  # USDT
  - addressOrDenom: "0xA670C3C0Cad4b941A74De4B040A8Fe2dCFf6AD02"
    chainName: blockx
    connections:
      - token: ethereum|bsc|0x8257c73b5112CCf727619cc01034E6e5E8C776E6
      - token: ethereum|polygon|0x9956A1Fc483b978505bA6233D7A22bEF33AEA968
    decimals: 6
    logoURI: '/logos/USDT_logo.svg'
    name: USDT
    standard: EvmHypSynthetic
    symbol: USDT
  - addressOrDenom: "0x8257c73b5112CCf727619cc01034E6e5E8C776E6"
    chainName: bsc
    collateralAddressOrDenom: "0x55d398326f99059ff775485246999027b3197955"
    connections:
      - token: ethereum|blockx|0xA670C3C0Cad4b941A74De4B040A8Fe2dCFf6AD02
    decimals: 18
    logoURI: '/logos/USDT_logo.svg'
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
  - addressOrDenom: "0x9956A1Fc483b978505bA6233D7A22bEF33AEA968"
    chainName: polygon
    collateralAddressOrDenom: "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"
    connections:
      - token: ethereum|blockx|0xA670C3C0Cad4b941A74De4B040A8Fe2dCFf6AD02
    decimals: 6
    logoURI: '/logos/USDT_logo.svg'
    name: USDT
    standard: EvmHypCollateral
    symbol: USDT
  # USDC
  - addressOrDenom: "0x5d63A5612994251Af6Be47AFE34F7Bd9D04861ce"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0xC726d5C214eE33AF9Fe9De0a2D78D5402eBDA299
      - token: ethereum|bsc|0xC08fD527aD84F454351a82eF22C3c2dF67FCA99D
    decimals: 6
    logoURI: '/logos/USDC_logo.svg'
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xC726d5C214eE33AF9Fe9De0a2D78D5402eBDA299"
    chainName: polygon
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    connections:
      - token: ethereum|blockx|0x5d63A5612994251Af6Be47AFE34F7Bd9D04861ce
    decimals: 6
    logoURI: '/logos/USDC_logo.svg'
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xC08fD527aD84F454351a82eF22C3c2dF67FCA99D"
    chainName: bsc
    collateralAddressOrDenom: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
    connections:
      - token: ethereum|blockx|0x5d63A5612994251Af6Be47AFE34F7Bd9D04861ce
    decimals: 18
    logoURI: '/logos/USDC_logo.svg'
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  # Polygon-Blockx BCX
  - addressOrDenom: "0xef67eBfbcc8E6A9E6F1dc9bAa7a4900C3194a08A"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0xb9D75Cd1d6dE1ECc6Cf60731e4643dA58eD918DE
    decimals: 18
    logoURI: '/logos/logo.svg'
    name: BlockX
    standard: EvmHypNative
    symbol: BCX
  - addressOrDenom: "0xb9D75Cd1d6dE1ECc6Cf60731e4643dA58eD918DE"
    chainName: polygon
    collateralAddressOrDenom: "0x871531a59Ef89C5262bCF58a80AB29F9711EA5a7"
    connections:
      - token: ethereum|blockx|0xef67eBfbcc8E6A9E6F1dc9bAa7a4900C3194a08A
    decimals: 18
    logoURI: '/logos/logo.svg'
    name: BlockX
    standard: EvmHypCollateral
    symbol: BCX
  # Polygon-BCX POL Token
  - addressOrDenom: "0xB7749d3535b15c84574ba506b5d3b08711b645a2"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0x54f4f01672D5DF0aC875280C44d75707ae9055a5
    decimals: 18
    logoURI: '/logos/POL_logo.svg'
    name: Polygon Ecosystem Token
    standard: EvmHypSynthetic
    symbol: POL
  - addressOrDenom: "0x54f4f01672D5DF0aC875280C44d75707ae9055a5"
    chainName: polygon
    connections:
      - token: ethereum|blockx|0xB7749d3535b15c84574ba506b5d3b08711b645a2
    decimals: 18
    logoURI: '/logos/POL_logo.svg'
    name: Polygon Ecosystem Token
    standard: EvmHypNative
    symbol: POL
  # BSC - Blockx BNB Token
  - addressOrDenom: "0xE31979EA671cC69913d53f46f03232a862BbF1FA"
    chainName: blockx
    connections:
      - token: ethereum|bsc|0x73234eDCa16BB09F459DDE9D0601eba23c63030d
    decimals: 18
    logoURI: '/logos/BNB_logo.svg'
    name: BNB
    standard: EvmHypSynthetic
    symbol: BNB
  - addressOrDenom: "0x73234eDCa16BB09F459DDE9D0601eba23c63030d"
    chainName: bsc
    connections:
      - token: ethereum|blockx|0xE31979EA671cC69913d53f46f03232a862BbF1FA
    decimals: 18
    logoURI: '/logos/BNB_logo.svg'
    name: BNB
    standard: EvmHypNative
    symbol: BNB
options: {}
