# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  # Polygon-Blockx USDT
  - addressOrDenom: "0x2f174aEac9fAD6e64760882AF4cb1DcB62921A10"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0xebf73db497e984aD6d0544eA30158E480a9780f5
    decimals: 6
    logoURI: '/logos/USDT_logo.svg'
    name: USDT0
    standard: EvmHypSynthetic
    symbol: USDT0
  - addressOrDenom: "0xebf73db497e984aD6d0544eA30158E480a9780f5"
    chainName: polygon
    collateralAddressOrDenom: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
    connections:
      - token: ethereum|blockx|0x2f174aEac9fAD6e64760882AF4cb1DcB62921A10
    decimals: 6
    logoURI: '/logos/USDT_logo.svg'
    name: USDT0
    standard: EvmHypCollateral
    symbol: USDT0
  # Polygon-Blockx USDC
  - addressOrDenom: "0x5d63A5612994251Af6Be47AFE34F7Bd9D04861ce"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0xC726d5C214eE33AF9Fe9De0a2D78D5402eBDA299
    decimals: 6
    logoURI: '/logos/USDC_logo.svg'
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xC726d5C214eE33AF9Fe9De0a2D78D5402eBDA299"
    chainName: polygon
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    connections:
      - token: ethereum|blockx|0x5d63A5612994251Af6Be47AFE34F7Bd9D04861ce
    decimals: 6
    logoURI: '/logos/USDC_logo.svg'
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
  # Polygon-Blockx BCX
  - addressOrDenom: "0xef67eBfbcc8E6A9E6F1dc9bAa7a4900C3194a08A"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0xb9D75Cd1d6dE1ECc6Cf60731e4643dA58eD918DE
    decimals: 18
    logoURI: '/logos/logo.svg'
    name: BlockX
    standard: EvmHypNative
    symbol: BCX
  - addressOrDenom: "0xb9D75Cd1d6dE1ECc6Cf60731e4643dA58eD918DE"
    chainName: polygon
    collateralAddressOrDenom: "0x871531a59Ef89C5262bCF58a80AB29F9711EA5a7"
    connections:
      - token: ethereum|blockx|0xef67eBfbcc8E6A9E6F1dc9bAa7a4900C3194a08A
    decimals: 18
    logoURI: '/logos/logo.svg'
    name: BlockX
    standard: EvmHypCollateral
    symbol: BCX
  # POL Token
  - addressOrDenom: "0xB7749d3535b15c84574ba506b5d3b08711b645a2"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0x54f4f01672D5DF0aC875280C44d75707ae9055a5
    decimals: 18
    logoURI: '/logos/POL_logo.svg'
    name: Polygon Ecosystem Token
    standard: EvmHypSynthetic
    symbol: POL
  - addressOrDenom: "0x54f4f01672D5DF0aC875280C44d75707ae9055a5"
    chainName: polygon
    connections:
      - token: ethereum|blockx|0xB7749d3535b15c84574ba506b5d3b08711b645a2
    decimals: 18
    logoURI: '/logos/POL_logo.svg'
    name: Polygon Ecosystem Token
    standard: EvmHypNative
    symbol: POL
options: {}
